
package com.xignite.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XigniteCurrenciesSoap", targetNamespace = "http://www.xignite.com/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XigniteCurrenciesSoap {


    /**
     * List supported currencies.
     * 
     * @return
     *     returns com.xignite.services.CurrencyList
     */
    @WebMethod(operationName = "ListCurrencies", action = "http://www.xignite.com/services/ListCurrencies")
    @WebResult(name = "ListCurrenciesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ListCurrencies", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListCurrencies")
    @ResponseWrapper(localName = "ListCurrenciesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListCurrenciesResponse")
    public CurrencyList listCurrencies();

    /**
     * List supported currencies.
     * 
     * @return
     *     returns com.xignite.services.CurrencyList
     */
    @WebMethod(operationName = "ListActiveCurrencies", action = "http://www.xignite.com/services/ListActiveCurrencies")
    @WebResult(name = "ListActiveCurrenciesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ListActiveCurrencies", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListActiveCurrencies")
    @ResponseWrapper(localName = "ListActiveCurrenciesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListActiveCurrenciesResponse")
    public CurrencyList listActiveCurrencies();

    /**
     * List supported official rates.
     * 
     * @return
     *     returns com.xignite.services.OfficialRates
     */
    @WebMethod(operationName = "ListOfficialRates", action = "http://www.xignite.com/services/ListOfficialRates")
    @WebResult(name = "ListOfficialRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ListOfficialRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListOfficialRates")
    @ResponseWrapper(localName = "ListOfficialRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListOfficialRatesResponse")
    public OfficialRates listOfficialRates();

    /**
     * Get Unit Of Account.
     * 
     * @param currency
     * @param asOfDate
     * @return
     *     returns com.xignite.services.UnitOfAccount
     */
    @WebMethod(operationName = "GetUnitOfAccount", action = "http://www.xignite.com/services/GetUnitOfAccount")
    @WebResult(name = "GetUnitOfAccountResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetUnitOfAccount", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetUnitOfAccount")
    @ResponseWrapper(localName = "GetUnitOfAccountResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetUnitOfAccountResponse")
    public UnitOfAccount getUnitOfAccount(
        @WebParam(name = "Currency", targetNamespace = "http://www.xignite.com/services/")
        String currency,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Convert value from one currency to another in real-time.
     * 
     * @param amount
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.ExchangeConversion
     */
    @WebMethod(operationName = "ConvertRealTimeValue", action = "http://www.xignite.com/services/ConvertRealTimeValue")
    @WebResult(name = "ConvertRealTimeValueResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ConvertRealTimeValue", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertRealTimeValue")
    @ResponseWrapper(localName = "ConvertRealTimeValueResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertRealTimeValueResponse")
    public ExchangeConversion convertRealTimeValue(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to,
        @WebParam(name = "Amount", targetNamespace = "http://www.xignite.com/services/")
        double amount);

    /**
     * Convert value from one currency to another as of a historical date.
     * 
     * @param amount
     * @param from
     * @param to
     * @param asOfDate
     * @return
     *     returns com.xignite.services.ExchangeConversion
     */
    @WebMethod(operationName = "ConvertHistoricalValue", action = "http://www.xignite.com/services/ConvertHistoricalValue")
    @WebResult(name = "ConvertHistoricalValueResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "ConvertHistoricalValue", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertHistoricalValue")
    @ResponseWrapper(localName = "ConvertHistoricalValueResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertHistoricalValueResponse")
    public ExchangeConversion convertHistoricalValue(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate,
        @WebParam(name = "Amount", targetNamespace = "http://www.xignite.com/services/")
        double amount);

    /**
     * Returns a set of real-time currency forward rates.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.ForwardRate
     */
    @WebMethod(operationName = "GetRealTimeForwardRate", action = "http://www.xignite.com/services/GetRealTimeForwardRate")
    @WebResult(name = "GetRealTimeForwardRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeForwardRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeForwardRate")
    @ResponseWrapper(localName = "GetRealTimeForwardRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeForwardRateResponse")
    public ForwardRate getRealTimeForwardRate(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to);

    /**
     * Returns a real-time currency cross-rate.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.CrossRate
     */
    @WebMethod(operationName = "GetRealTimeCrossRateAsString", action = "http://www.xignite.com/services/GetRealTimeCrossRateAsString")
    @WebResult(name = "GetRealTimeCrossRateAsStringResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRateAsString", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateAsString")
    @ResponseWrapper(localName = "GetRealTimeCrossRateAsStringResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateAsStringResponse")
    public CrossRate getRealTimeCrossRateAsString(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to);

    /**
     * Returns the latest possible cross rate.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.CrossRate
     */
    @WebMethod(operationName = "GetLatestCrossRate", action = "http://www.xignite.com/services/GetLatestCrossRate")
    @WebResult(name = "GetLatestCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetLatestCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRate")
    @ResponseWrapper(localName = "GetLatestCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRateResponse")
    public CrossRate getLatestCrossRate(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to);

    /**
     * Returns the latest possible cross rate.
     * 
     * @param tos
     * @param from
     * @return
     *     returns com.xignite.services.ArrayOfCrossRate
     */
    @WebMethod(operationName = "GetLatestCrossRates", action = "http://www.xignite.com/services/GetLatestCrossRates")
    @WebResult(name = "GetLatestCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetLatestCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRates")
    @ResponseWrapper(localName = "GetLatestCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRatesResponse")
    public ArrayOfCrossRate getLatestCrossRates(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "Tos", targetNamespace = "http://www.xignite.com/services/")
        String tos);

    /**
     * Returns a real-time currency cross-rate.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.CrossRate
     */
    @WebMethod(operationName = "GetRealTimeCrossRate", action = "http://www.xignite.com/services/GetRealTimeCrossRate")
    @WebResult(name = "GetRealTimeCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRate")
    @ResponseWrapper(localName = "GetRealTimeCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateResponse")
    public CrossRate getRealTimeCrossRate(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        Currencies to);

    /**
     * Returns a real-time currency cross-rate with the times in GMT.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.CrossRate
     */
    @WebMethod(operationName = "GetRealTimeCrossRateGMT", action = "http://www.xignite.com/services/GetRealTimeCrossRateGMT")
    @WebResult(name = "GetRealTimeCrossRateGMTResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRateGMT", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateGMT")
    @ResponseWrapper(localName = "GetRealTimeCrossRateGMTResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateGMTResponse")
    public CrossRate getRealTimeCrossRateGMT(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        Currencies to);

    /**
     * Returns a real-time currency cross-rate.
     * 
     * @param from
     * @param to
     * @return
     *     returns com.xignite.services.CrossRate
     */
    @WebMethod(operationName = "GetRawCrossRate", action = "http://www.xignite.com/services/GetRawCrossRate")
    @WebResult(name = "GetRawCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRawCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRate")
    @ResponseWrapper(localName = "GetRawCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRateResponse")
    public CrossRate getRawCrossRate(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        Currencies to);

    /**
     * Returns a real-time currency cross-rate.
     * 
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfCrossRate
     */
    @WebMethod(operationName = "GetRawCrossRates", action = "http://www.xignite.com/services/GetRawCrossRates")
    @WebResult(name = "GetRawCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRawCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRates")
    @ResponseWrapper(localName = "GetRawCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRatesResponse")
    public ArrayOfCrossRate getRawCrossRates(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols);

    /**
     * Returns the latest possible cross rate.
     * 
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfCrossRate
     */
    @WebMethod(operationName = "GetRealTimeCrossRates", action = "http://www.xignite.com/services/GetRealTimeCrossRates")
    @WebResult(name = "GetRealTimeCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRates")
    @ResponseWrapper(localName = "GetRealTimeCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRatesResponse")
    public ArrayOfCrossRate getRealTimeCrossRates(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols);

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     * 
     * @param endDate
     * @param symbols
     * @param startDate
     * @return
     *     returns com.xignite.services.ArrayOfCrossRateTable
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTables", action = "http://www.xignite.com/services/GetHistoricalCrossRateTables")
    @WebResult(name = "GetHistoricalCrossRateTablesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateTables", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTables")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTablesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesResponse")
    public ArrayOfCrossRateTable getHistoricalCrossRateTables(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     * 
     * @param endDate
     * @param symbols
     * @param startDate
     * @return
     *     returns com.xignite.services.ArrayOfCrossRateTableWithBidAsk
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTablesBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateTablesBidAsk")
    @WebResult(name = "GetHistoricalCrossRateTablesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateTablesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTablesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesBidAskResponse")
    public ArrayOfCrossRateTableWithBidAsk getHistoricalCrossRateTablesBidAsk(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     * 
     * @param endDate
     * @param from
     * @param to
     * @param startDate
     * @return
     *     returns com.xignite.services.Report
     */
    @WebMethod(operationName = "GetCurrencyReport", action = "http://www.xignite.com/services/GetCurrencyReport")
    @WebResult(name = "GetCurrencyReportResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyReport", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyReport")
    @ResponseWrapper(localName = "GetCurrencyReportResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyReportResponse")
    public Report getCurrencyReport(
        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        String to,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * Returns a historical currency cross-rate table.
     * 
     * @param asOfDate
     * @param symbols
     * @return
     *     returns com.xignite.services.CrossRateTable
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTable", action = "http://www.xignite.com/services/GetHistoricalCrossRateTable")
    @WebResult(name = "GetHistoricalCrossRateTableResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateTable", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTable")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableResponse")
    public CrossRateTable getHistoricalCrossRateTable(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns a historical currency cross-rate table.
     * 
     * @param asOfDate
     * @param symbols
     * @return
     *     returns com.xignite.services.CrossRateTableWithBidAsk
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTableBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateTableBidAsk")
    @WebResult(name = "GetHistoricalCrossRateTableBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateTableBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableBidAskResponse")
    public CrossRateTableWithBidAsk getHistoricalCrossRateTableBidAsk(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns a real-time currency cross-rate table.
     * 
     * @param symbols
     * @return
     *     returns com.xignite.services.CrossRateTable
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTable", action = "http://www.xignite.com/services/GetRealTimeCrossRateTable")
    @WebResult(name = "GetRealTimeCrossRateTableResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRateTable", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTable")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableResponse")
    public CrossRateTable getRealTimeCrossRateTable(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols);

    /**
     * Returns a real-time currency cross-rate table.
     * 
     * @param symbols
     * @return
     *     returns com.xignite.services.CrossRateTableWithBidAsk
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTableWithBidAsk", action = "http://www.xignite.com/services/GetRealTimeCrossRateTableWithBidAsk")
    @WebResult(name = "GetRealTimeCrossRateTableWithBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRateTableWithBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableWithBidAsk")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableWithBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableWithBidAskResponse")
    public CrossRateTableWithBidAsk getRealTimeCrossRateTableWithBidAsk(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols);

    /**
     * Returns all valid cross rates for a currency.
     * 
     * @param symbol
     * @return
     *     returns com.xignite.services.CrossRateTableLineWithBidAsk
     */
    @WebMethod(operationName = "GetAllCrossRatesForACurrency", action = "http://www.xignite.com/services/GetAllCrossRatesForACurrency")
    @WebResult(name = "GetAllCrossRatesForACurrencyResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAllCrossRatesForACurrency", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllCrossRatesForACurrency")
    @ResponseWrapper(localName = "GetAllCrossRatesForACurrencyResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllCrossRatesForACurrencyResponse")
    public CrossRateTableLineWithBidAsk getAllCrossRatesForACurrency(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol);

    /**
     * Returns a real-time currency cross-rate table as an HTML Output.
     * 
     * @param lineHeaderStyle
     * @param columnHeaderStyle
     * @param cellStyle
     * @param symbols
     * @return
     *     returns com.xignite.services.HTMLCrossRateTable
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetRealTimeCrossRateTableAsHTML")
    @WebResult(name = "GetRealTimeCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetRealTimeCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableAsHTMLResponse")
    public HTMLCrossRateTable getRealTimeCrossRateTableAsHTML(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        String cellStyle);

    /**
     * Returns a real-time currency cross-rate table as an HTML Output.
     * 
     * @param lineHeaderStyle
     * @param columnHeaderStyle
     * @param cellStyle
     * @param symbols
     * @return
     *     returns com.xignite.services.HTMLCrossRateTable
     */
    @WebMethod(operationName = "GetSimpleRealTimeCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetSimpleRealTimeCrossRateTableAsHTML")
    @WebResult(name = "GetSimpleRealTimeCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetSimpleRealTimeCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSimpleRealTimeCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetSimpleRealTimeCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSimpleRealTimeCrossRateTableAsHTMLResponse")
    public HTMLCrossRateTable getSimpleRealTimeCrossRateTableAsHTML(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        String cellStyle);

    /**
     * Returns a historical currency cross-rate table as an HTML Output.
     * 
     * @param lineHeaderStyle
     * @param asOfDate
     * @param columnHeaderStyle
     * @param cellStyle
     * @param symbols
     * @return
     *     returns com.xignite.services.HTMLCrossRateTable
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetHistoricalCrossRateTableAsHTML")
    @WebResult(name = "GetHistoricalCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableAsHTMLResponse")
    public HTMLCrossRateTable getHistoricalCrossRateTableAsHTML(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        String cellStyle);

    /**
     * Returns a cross-rate as of a historical date.
     * 
     * @param symbol
     * @param asOfDate
     * @return
     *     returns com.xignite.services.HistoricalCrossRate
     */
    @WebMethod(operationName = "GetHistoricalCrossRate", action = "http://www.xignite.com/services/GetHistoricalCrossRate")
    @WebResult(name = "GetHistoricalCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRate")
    @ResponseWrapper(localName = "GetHistoricalCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateResponse")
    public HistoricalCrossRate getHistoricalCrossRate(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns multiple cross-rates as of a historical date.
     * 
     * @param asOfDate
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfHistoricalCrossRate
     */
    @WebMethod(operationName = "GetHistoricalCrossRates", action = "http://www.xignite.com/services/GetHistoricalCrossRates")
    @WebResult(name = "GetHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRates")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesResponse")
    public ArrayOfHistoricalCrossRate getHistoricalCrossRates(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns a cross-rate with bid/ask as of a historical date.
     * 
     * @param symbol
     * @param asOfDate
     * @return
     *     returns com.xignite.services.FullHistoricalCrossRate
     */
    @WebMethod(operationName = "GetHistoricalCrossRateBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateBidAsk")
    @WebResult(name = "GetHistoricalCrossRateBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRateBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateBidAskResponse")
    public FullHistoricalCrossRate getHistoricalCrossRateBidAsk(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns multiple cross-rates with bid/ask as of a historical date.
     * 
     * @param asOfDate
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfFullHistoricalCrossRate
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAsk")
    @WebResult(name = "GetHistoricalCrossRatesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskResponse")
    public ArrayOfFullHistoricalCrossRate getHistoricalCrossRatesBidAsk(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * This operation returns a range of cross-rates for a currency pair. 
     * 
     * @param symbol
     * @param endDate
     * @param startDate
     * @return
     *     returns com.xignite.services.HistoricalCrossRates
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesRange", action = "http://www.xignite.com/services/GetHistoricalCrossRatesRange")
    @WebResult(name = "GetHistoricalCrossRatesRangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRatesRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesRange")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesRangeResponse")
    public HistoricalCrossRates getHistoricalCrossRatesRange(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * This operation returns a range of cross-rates for a currency pair. 
     * 
     * @param symbol
     * @param endDate
     * @param startDate
     * @return
     *     returns com.xignite.services.FullHistoricalCrossRates
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAskRange", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAskRange")
    @WebResult(name = "GetHistoricalCrossRatesBidAskRangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAskRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskRange")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskRangeResponse")
    public FullHistoricalCrossRates getHistoricalCrossRatesBidAskRange(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * This operation returns a range of cross-rates for a currency pair.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param periods
     * @return
     *     returns com.xignite.services.HistoricalCrossRates
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesAsOf", action = "http://www.xignite.com/services/GetHistoricalCrossRatesAsOf")
    @WebResult(name = "GetHistoricalCrossRatesAsOfResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRatesAsOf", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesAsOf")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesAsOfResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesAsOfResponse")
    public HistoricalCrossRates getHistoricalCrossRatesAsOf(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        PeriodTypes periodType,
        @WebParam(name = "Periods", targetNamespace = "http://www.xignite.com/services/")
        int periods);

    /**
     * This operation returns a range of cross-rates for a currency pair.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param periods
     * @return
     *     returns com.xignite.services.FullHistoricalCrossRates
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAskAsOf", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAskAsOf")
    @WebResult(name = "GetHistoricalCrossRatesBidAskAsOfResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAskAsOf", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskAsOf")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskAsOfResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskAsOfResponse")
    public FullHistoricalCrossRates getHistoricalCrossRatesBidAskAsOf(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        PeriodTypes periodType,
        @WebParam(name = "Periods", targetNamespace = "http://www.xignite.com/services/")
        int periods);

    /**
     * Returns an official cross-rate as of a historical date.
     * 
     * @param symbol
     * @param asOfDate
     * @param countryType
     * @return
     *     returns com.xignite.services.HistoricalCrossRate
     */
    @WebMethod(operationName = "GetOfficialCrossRate", action = "http://www.xignite.com/services/GetOfficialCrossRate")
    @WebResult(name = "GetOfficialCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOfficialCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRate")
    @ResponseWrapper(localName = "GetOfficialCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateResponse")
    public HistoricalCrossRate getOfficialCrossRate(
        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        CountryTypes countryType,
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        Currencies symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns an official cross-rate as of a historical date.
     * 
     * @param asOfDate
     * @param countryType
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfHistoricalCrossRate
     */
    @WebMethod(operationName = "GetOfficialCrossRates", action = "http://www.xignite.com/services/GetOfficialCrossRates")
    @WebResult(name = "GetOfficialCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOfficialCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRates")
    @ResponseWrapper(localName = "GetOfficialCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesResponse")
    public ArrayOfHistoricalCrossRate getOfficialCrossRates(
        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        CountryTypes countryType,
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns an official cross-rate as of a historical date.
     * 
     * @param symbol
     * @param asOfDate
     * @param countryType
     * @return
     *     returns com.xignite.services.FullHistoricalCrossRate
     */
    @WebMethod(operationName = "GetOfficialCrossRateBidAsk", action = "http://www.xignite.com/services/GetOfficialCrossRateBidAsk")
    @WebResult(name = "GetOfficialCrossRateBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOfficialCrossRateBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateBidAsk")
    @ResponseWrapper(localName = "GetOfficialCrossRateBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateBidAskResponse")
    public FullHistoricalCrossRate getOfficialCrossRateBidAsk(
        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        CountryTypes countryType,
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        Currencies symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns an official cross-rate as of a historical date.
     * 
     * @param asOfDate
     * @param countryType
     * @param symbols
     * @return
     *     returns com.xignite.services.ArrayOfFullHistoricalCrossRate
     */
    @WebMethod(operationName = "GetOfficialCrossRatesBidAsk", action = "http://www.xignite.com/services/GetOfficialCrossRatesBidAsk")
    @WebResult(name = "GetOfficialCrossRatesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetOfficialCrossRatesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesBidAsk")
    @ResponseWrapper(localName = "GetOfficialCrossRatesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesBidAskResponse")
    public ArrayOfFullHistoricalCrossRate getOfficialCrossRatesBidAsk(
        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        CountryTypes countryType,
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * Returns multiple cross-rates as of a historical date.
     * 
     * @param asOfDate
     * @param symbols
     * @return
     *     returns com.xignite.services.MultipleHistoricalCrossRates
     */
    @WebMethod(operationName = "GetMutipleHistoricalCrossRates", action = "http://www.xignite.com/services/GetMutipleHistoricalCrossRates")
    @WebResult(name = "GetMutipleHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetMutipleHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMutipleHistoricalCrossRates")
    @ResponseWrapper(localName = "GetMutipleHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMutipleHistoricalCrossRatesResponse")
    public MultipleHistoricalCrossRates getMutipleHistoricalCrossRates(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate);

    /**
     * This operation returns an array average daily historical cross-rates for a period. 
     * 
     * @param endDate
     * @param symbols
     * @param startDate
     * @return
     *     returns com.xignite.services.ArrayOfAverageHistoricalCrossRate
     */
    @WebMethod(operationName = "GetAverageHistoricalCrossRates", action = "http://www.xignite.com/services/GetAverageHistoricalCrossRates")
    @WebResult(name = "GetAverageHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAverageHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRates")
    @ResponseWrapper(localName = "GetAverageHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRatesResponse")
    public ArrayOfAverageHistoricalCrossRate getAverageHistoricalCrossRates(
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * This operation returns an average daily historical cross-rates for a period. 
     * 
     * @param symbol
     * @param endDate
     * @param startDate
     * @return
     *     returns com.xignite.services.AverageHistoricalCrossRate
     */
    @WebMethod(operationName = "GetAverageHistoricalCrossRate", action = "http://www.xignite.com/services/GetAverageHistoricalCrossRate")
    @WebResult(name = "GetAverageHistoricalCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetAverageHistoricalCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRate")
    @ResponseWrapper(localName = "GetAverageHistoricalCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRateResponse")
    public AverageHistoricalCrossRate getAverageHistoricalCrossRate(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * This operation returns a complete range of stock quotes for a currency pair.
     * 
     * @param symbol
     * @param endDate
     * @param startDate
     * @return
     *     returns com.xignite.services.FullHistoricalCrossRates
     */
    @WebMethod(operationName = "GetHistoricalMonthlyCrossRatesRange", action = "http://www.xignite.com/services/GetHistoricalMonthlyCrossRatesRange")
    @WebResult(name = "GetHistoricalMonthlyCrossRatesRangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalMonthlyCrossRatesRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyCrossRatesRange")
    @ResponseWrapper(localName = "GetHistoricalMonthlyCrossRatesRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyCrossRatesRangeResponse")
    public FullHistoricalCrossRates getHistoricalMonthlyCrossRatesRange(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate);

    /**
     * This operation returns the changes in a cross-rates over the last 6 months. 
     * 
     * @param symbol
     * @return
     *     returns com.xignite.services.CrossRateChange
     */
    @WebMethod(operationName = "GetCrossRateChange", action = "http://www.xignite.com/services/GetCrossRateChange")
    @WebResult(name = "GetCrossRateChangeResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCrossRateChange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCrossRateChange")
    @ResponseWrapper(localName = "GetCrossRateChangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCrossRateChangeResponse")
    public CrossRateChange getCrossRateChange(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol);

    /**
     * Draw a custom currency chart for a date range.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param design
     * @param width
     * @param style
     * @param startDate
     * @param height
     * @return
     *     returns com.xignite.services.HistoricalChart
     */
    @WebMethod(operationName = "GetCurrencyChartCustom", action = "http://www.xignite.com/services/GetCurrencyChartCustom")
    @WebResult(name = "GetCurrencyChartCustomResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyChartCustom", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustom")
    @ResponseWrapper(localName = "GetCurrencyChartCustomResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomResponse")
    public HistoricalChart getCurrencyChartCustom(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        ChartDesign design);

    /**
     * Draw a custom currency chart for a date range.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param design
     * @param width
     * @param style
     * @param startDate
     * @param height
     * @return
     *     returns com.xignite.services.ChartBinary
     */
    @WebMethod(operationName = "GetCurrencyChartCustomBinary", action = "http://www.xignite.com/services/GetCurrencyChartCustomBinary")
    @WebResult(name = "GetCurrencyChartCustomBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyChartCustomBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomBinary")
    @ResponseWrapper(localName = "GetCurrencyChartCustomBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomBinaryResponse")
    public ChartBinary getCurrencyChartCustomBinary(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        ChartDesign design);

    /**
     * Draw a historical currency chart for a date range.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param width
     * @param style
     * @param preset
     * @param startDate
     * @param height
     * @return
     *     returns com.xignite.services.HistoricalChart
     */
    @WebMethod(operationName = "GetCurrencyChart", action = "http://www.xignite.com/services/GetCurrencyChart")
    @WebResult(name = "GetCurrencyChartResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyChart", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChart")
    @ResponseWrapper(localName = "GetCurrencyChartResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartResponse")
    public HistoricalChart getCurrencyChart(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        String preset);

    /**
     * Draw a historical currency chart for a date range in binary format.
     * 
     * @param symbol
     * @param periodType
     * @param endDate
     * @param width
     * @param style
     * @param preset
     * @param startDate
     * @param height
     * @return
     *     returns com.xignite.services.ChartBinary
     */
    @WebMethod(operationName = "GetCurrencyChartBinary", action = "http://www.xignite.com/services/GetCurrencyChartBinary")
    @WebResult(name = "GetCurrencyChartBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyChartBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartBinary")
    @ResponseWrapper(localName = "GetCurrencyChartBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartBinaryResponse")
    public ChartBinary getCurrencyChartBinary(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        String preset);

    /**
     * Draw a intraday currency chart for a time range
     * 
     * @param symbol
     * @param periodType
     * @param width
     * @param timeZone
     * @param startTime
     * @param style
     * @param endTime
     * @param preset
     * @param tickPeriods
     * @param height
     * @return
     *     returns com.xignite.services.CurrencyChartIntraday
     */
    @WebMethod(operationName = "GetCurrencyIntradayChart", action = "http://www.xignite.com/services/GetCurrencyIntradayChart")
    @WebResult(name = "GetCurrencyIntradayChartResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyIntradayChart", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChart")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartResponse")
    public CurrencyChartIntraday getCurrencyIntradayChart(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        String preset);

    /**
     * Draw a intraday currency chart for a time range in a binary format
     * 
     * @param symbol
     * @param periodType
     * @param design
     * @param width
     * @param timeZone
     * @param startTime
     * @param style
     * @param endTime
     * @param tickPeriods
     * @param height
     * @return
     *     returns com.xignite.services.ChartBinary
     */
    @WebMethod(operationName = "GetCurrencyIntradayChartCustomBinary", action = "http://www.xignite.com/services/GetCurrencyIntradayChartCustomBinary")
    @WebResult(name = "GetCurrencyIntradayChartCustomBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyIntradayChartCustomBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomBinary")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartCustomBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomBinaryResponse")
    public ChartBinary getCurrencyIntradayChartCustomBinary(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        ChartDesign design);

    /**
     * Draw a intraday currency chart for a time range in a binary format
     * 
     * @param symbol
     * @param periodType
     * @param design
     * @param width
     * @param timeZone
     * @param startTime
     * @param style
     * @param endTime
     * @param tickPeriods
     * @param height
     * @return
     *     returns com.xignite.services.CurrencyChartIntraday
     */
    @WebMethod(operationName = "GetCurrencyIntradayChartCustom", action = "http://www.xignite.com/services/GetCurrencyIntradayChartCustom")
    @WebResult(name = "GetCurrencyIntradayChartCustomResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetCurrencyIntradayChartCustom", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustom")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartCustomResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomResponse")
    public CurrencyChartIntraday getCurrencyIntradayChartCustom(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        ChartDesign design);

    /**
     * Returns the default design class for the currency Chart.
     * 
     * @return
     *     returns com.xignite.services.ChartDesign
     */
    @WebMethod(operationName = "GetChartDesign", action = "http://www.xignite.com/services/GetChartDesign")
    @WebResult(name = "GetChartDesignResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetChartDesign", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetChartDesign")
    @ResponseWrapper(localName = "GetChartDesignResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetChartDesignResponse")
    public ChartDesign getChartDesign();

    /**
     * Returns a tick for a currency pair as of a specific time in the day.
     * 
     * @param symbol
     * @param time
     * @return
     *     returns com.xignite.services.SingleTick
     */
    @WebMethod(operationName = "GetTick", action = "http://www.xignite.com/services/GetTick")
    @WebResult(name = "GetTickResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetTick", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTick")
    @ResponseWrapper(localName = "GetTickResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTickResponse")
    public SingleTick getTick(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "Time", targetNamespace = "http://www.xignite.com/services/")
        String time);

    /**
     * Returns a range of ticks for a currency pair.
     * 
     * @param symbol
     * @param startTime
     * @param endTime
     * @param tickPrecision
     * @param tickPeriods
     * @return
     *     returns com.xignite.services.Ticks
     */
    @WebMethod(operationName = "GetTicks", action = "http://www.xignite.com/services/GetTicks")
    @WebResult(name = "GetTicksResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetTicks", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTicks")
    @ResponseWrapper(localName = "GetTicksResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTicksResponse")
    public Ticks getTicks(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        String endTime,
        @WebParam(name = "TickPrecision", targetNamespace = "http://www.xignite.com/services/")
        TickPeriod tickPrecision,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods);

    /**
     * Returns a range of ticks for a currency pair.
     * 
     * @param symbol
     * @param startTime
     * @param endTime
     * @param tickPrecision
     * @param asOfDate
     * @param tickPeriods
     * @return
     *     returns com.xignite.services.Ticks
     */
    @WebMethod(operationName = "GetHistoricalTicks", action = "http://www.xignite.com/services/GetHistoricalTicks")
    @WebResult(name = "GetHistoricalTicksResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalTicks", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalTicks")
    @ResponseWrapper(localName = "GetHistoricalTicksResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalTicksResponse")
    public Ticks getHistoricalTicks(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        String endTime,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        String asOfDate,
        @WebParam(name = "TickPrecision", targetNamespace = "http://www.xignite.com/services/")
        TickPeriod tickPrecision,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods);

    /**
     * Returns the high and the low ticks for a historical time range.
     * 
     * @param symbol
     * @param startDateTime
     * @param endDateTime
     * @return
     *     returns com.xignite.services.HighLowTick
     */
    @WebMethod(operationName = "GetHistoricalHighLow", action = "http://www.xignite.com/services/GetHistoricalHighLow")
    @WebResult(name = "GetHistoricalHighLowResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetHistoricalHighLow", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalHighLow")
    @ResponseWrapper(localName = "GetHistoricalHighLowResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalHighLowResponse")
    public HighLowTick getHistoricalHighLow(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.xignite.com/services/")
        String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.xignite.com/services/")
        String endDateTime);

    /**
     * Returns the high and the low ticks for today.
     * 
     * @param symbol
     * @param startDateTime
     * @param endDateTime
     * @return
     *     returns com.xignite.services.HighLowTick
     */
    @WebMethod(operationName = "GetIntradayHighLow", action = "http://www.xignite.com/services/GetIntradayHighLow")
    @WebResult(name = "GetIntradayHighLowResult", targetNamespace = "http://www.xignite.com/services/")
    @RequestWrapper(localName = "GetIntradayHighLow", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIntradayHighLow")
    @ResponseWrapper(localName = "GetIntradayHighLowResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIntradayHighLowResponse")
    public HighLowTick getIntradayHighLow(
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        String symbol,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.xignite.com/services/")
        String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.xignite.com/services/")
        String endDateTime);

}
